export interface EmployerAccount {
  id: string;
  email: string;
  companyName: string;
  tin: string;
  vrn: string;
  status: 'pending' | 'approved' | 'suspended';
  agreementSigned: boolean;
  agreementDate?: Date;
  digitalSignature?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface JobRequirement {
  id: string;
  employerId: string;
  position: string;
  jobDescription: string;
  jobRequirements: string;
  location: string;
  salaryRange: {
    min: number;
    max: number;
    currency: string;
  };
  viewToCandidates: boolean;
  testPaper?: {
    file: File;
    fileName: string;
    hasAnswerSheet: boolean;
  };
  status: 'draft' | 'submitted' | 'approved' | 'rejected' | 'published';
  submittedAt?: Date;
  approvedAt?: Date;
  publishedAt?: Date;
  autoGeneratedAd?: string;
  adminFeedback?: string;
}

export interface JobAdvertisement {
  id: string;
  jobRequirementId: string;
  title: string;
  description: string;
  requirements: string;
  salaryRange: string;
  location: string;
  type: 'full-time' | 'part-time' | 'contract';
  status: 'draft' | 'pending' | 'published' | 'expired';
  platforms: ('facebook' | 'instagram' | 'linkedin' | 'website')[];
  publishedAt?: Date;
  expiresAt?: Date;
}

export interface CandidateApplication {
  id: string;
  jobAdvertisementId: string;
  candidateId: string;
  status: 'applied' | 'shortlisted' | 'interviewed' | 'selected' | 'rejected';
  appliedAt: Date;
  shortlistedAt?: Date;
  interviewedAt?: Date;
  selectedAt?: Date;
  rejectedAt?: Date;
  employerFeedback?: string;
  interviewSchedule?: InterviewSchedule;
}

export interface InterviewSchedule {
  id: string;
  candidateApplicationId: string;
  scheduledDate: Date;
  scheduledTime: string;
  interviewer: string;
  location: string;
  status: 'scheduled' | 'confirmed' | 'rescheduled' | 'completed' | 'cancelled';
  notes?: string;
  rescheduledDate?: Date;
  rescheduledTime?: string;
}

export interface CandidateEvaluation {
  id: string;
  candidateApplicationId: string;
  technicalSkills: number; // 1-5
  communicationSkills: number; // 1-5
  experience: number; // 1-5
  culturalFit: number; // 1-5
  overallRating: number; // 1-5
  strengths: string[];
  weaknesses: string[];
  recommendations: string;
  evaluatorId: string;
  evaluatedAt: Date;
}

export interface ReferenceCheck {
  id: string;
  candidateApplicationId: string;
  refereeName: string;
  refereePosition: string;
  refereeCompany: string;
  refereeEmail: string;
  refereePhone: string;
  formSentAt: Date;
  formCompletedAt?: Date;
  relationship: string;
  workEthic: number; // 1-5
  technicalSkills: number; // 1-5
  reliability: number; // 1-5
  teamwork: number; // 1-5
  overallRecommendation: 'strongly_recommend' | 'recommend' | 'neutral' | 'not_recommend';
  additionalComments?: string;
  status: 'pending' | 'completed' | 'expired';
}

export interface Invoice {
  id: string;
  candidateApplicationId: string;
  employerId: string;
  amount: number;
  currency: string;
  description: string;
  invoiceNumber: string;
  sentDate: Date;
  dueDate: Date;
  paymentDate?: Date;
  status: 'sent' | 'paid' | 'overdue' | 'cancelled';
  paymentMethod?: string;
  notes?: string;
}

export interface EmployerDashboard {
  totalJobRequirements: number;
  pendingApprovals: number;
  activeJobPostings: number;
  totalApplications: number;
  shortlistedCandidates: number;
  interviewsScheduled: number;
  placements: number;
  outstandingInvoices: number;
  recentActivity: DashboardActivity[];
}

export interface DashboardActivity {
  id: string;
  type: 'job_submitted' | 'job_approved' | 'application_received' | 'candidate_shortlisted' | 'interview_scheduled' | 'placement_made' | 'invoice_sent';
  title: string;
  description: string;
  timestamp: Date;
  relatedId?: string;
}

export interface InterviewEvaluation {
  id: string;
  candidateId: string;
  jobId: string;
  interviewerName: string;
  interviewDate: string;
  interviewMode: 'online' | 'physical';

  // Ratings (Above/Satisfactory/Below/Unsatisfactory)
  technicalSkills: 'above' | 'satisfactory' | 'below' | 'unsatisfactory';
  communication: 'above' | 'satisfactory' | 'below' | 'unsatisfactory';
  leadership: 'above' | 'satisfactory' | 'below' | 'unsatisfactory';
  culturalFit: 'above' | 'satisfactory' | 'below' | 'unsatisfactory';
  overallRating: 'above' | 'satisfactory' | 'below' | 'unsatisfactory';

  // Comments
  strengths: string;
  weaknesses: string;
  comments: string;

  // Final recommendation
  recommendation: 'rejected' | 'can_be_considered' | 'recommended' | 'strongly_recommended';

  // Metadata
  evaluatedBy: string;
  evaluatedAt: string;
  isSubmittedToClient: boolean;
}

export interface InterviewDetails {
  id: string;
  candidateId: string;
  jobId: string;
  interviewDate: string;
  interviewTime: string;
  interviewerNames: string[];
  interviewMode: 'online' | 'physical';
  meetingLink?: string;
  location?: string;
  status: 'scheduled' | 'completed' | 'no_show';
  notes?: string;
  scheduledBy: string;
  scheduledAt: string;
}

export interface ApplicationStage {
  id: string;
  candidateId: string;
  jobId: string;
  stage: 'applications_received' | 'shortlisted' | 'interview_scheduled' | 'interviewed' | 'no_show' | 'submitted_to_client' | 'rejected' | 'saved_for_future';
  status: 'active' | 'completed';
  movedBy: string;
  movedAt: string;
  notes?: string;
  source: 'direct_application' | 'database_search' | 'talent_pool';
}

export interface ApplicationWorkflow {
  id: string;
  jobId: string;
  candidateId: string;
  currentStage: ApplicationStage['stage'];
  stages: ApplicationStage[];
  interviewDetails?: InterviewDetails;
  interviewEvaluation?: InterviewEvaluation;
  isLiked: boolean;
  createdAt: string;
  updatedAt: string;
} 