// Job titles organized by categories
export const jobTitles: { [key: string]: string[] } = {
  'Agriculture & Farming': [
    'Agricultural Technician',
    'Aquaculture Technician',
    'Dairy Worker',
    'Farm Labourer',
    'Farmer',
    'Fisherman',
    'Greenhouse Worker',
    'Irrigation Technician',
    'Poultry Worker',
    'Tractor Operator'
  ],
  'Construction & Labour': [
    'Bridge Worker',
    'Concrete Worker',
    'Construction Worker',
    'Demolition Worker',
    'Gardener',
    'General Labourer',
    'Helper Carpenter',
    'Helper Mason',
    'Landscaping Worker',
    'Road Worker',
    'Sandblaster',
    'Scaffolding Helper',
    'Steel Fixer',
    'Stone Cutter',
    'Tunnel Worker'
  ],
  'Construction, Real Estate & Facilities': [
    'Architect',
    'AutoCAD Drafter',
    'Civil Engineer',
    'Construction Manager',
    'Electrical Engineer',
    'Estate Manager',
    'Facility Manager',
    'Foreman',
    'HVAC Engineer',
    'Health and Safety Officer',
    'Junior AutoCAD Drafter',
    'Junior Civil Engineer',
    'Junior Electrical Engineer',
    'Junior HVAC Engineer',
    'Junior MEP Engineer',
    'Junior Mechanical Engineer',
    'Junior Plumbing Engineer',
    'Junior Project Engineer',
    'Junior Quantity Surveyor',
    'Junior Revit Modeler',
    'Junior Site Engineer',
    'Junior Structural Engineer',
    'Lead AutoCAD Drafter',
    'Lead Civil Engineer',
    'Lead Electrical Engineer',
    'Lead HVAC Engineer',
    'Lead MEP Engineer',
    'Lead Mechanical Engineer',
    'Lead Plumbing Engineer',
    'Lead Project Engineer',
    'Lead Quantity Surveyor',
    'Lead Revit Modeler',
    'Lead Site Engineer',
    'Lead Structural Engineer',
    'MEP Engineer',
    'Mechanical Engineer',
    'Plumbing Engineer',
    'Principal AutoCAD Drafter',
    'Principal Civil Engineer',
    'Principal Electrical Engineer',
    'Principal HVAC Engineer',
    'Principal MEP Engineer',
    'Principal Mechanical Engineer',
    'Principal Plumbing Engineer',
    'Principal Project Engineer',
    'Principal Quantity Surveyor',
    'Principal Revit Modeler',
    'Principal Site Engineer',
    'Principal Structural Engineer',
    'Project Engineer',
    'Project Manager (Construction)',
    'Property Manager',
    'Quantity Surveyor',
    'Revit Modeler',
    'Senior AutoCAD Drafter',
    'Senior Civil Engineer',
    'Senior Electrical Engineer',
    'Senior HVAC Engineer',
    'Senior MEP Engineer',
    'Senior Mechanical Engineer',
    'Senior Plumbing Engineer',
    'Senior Project Engineer',
    'Senior Quantity Surveyor',
    'Senior Revit Modeler',
    'Senior Site Engineer',
    'Senior Structural Engineer',
    'Site Engineer',
    'Site Supervisor',
    'Structural Engineer',
    'Urban Planner'
  ],
  'Customer Support & Success': [
    'Application Support Engineer',
    'Client Services Manager',
    'Customer Service Executive',
    'Customer Service Representative',
    'Customer Success Associate',
    'Customer Support Executive',
    'Customer Support Representative',
    'Help Desk Analyst',
    'Implementation Specialist',
    'Junior Application Support Engineer',
    'Junior Customer Service Executive',
    'Junior Customer Support Executive',
    'Junior Help Desk Analyst',
    'Junior Implementation Specialist',
    'Junior Onboarding Specialist',
    'Junior Service Desk Analyst',
    'Junior Technical Support Engineer',
    'Lead Application Support Engineer',
    'Lead Customer Service Executive',
    'Lead Customer Support Executive',
    'Lead Help Desk Analyst',
    'Lead Implementation Specialist',
    'Lead Onboarding Specialist',
    'Lead Service Desk Analyst',
    'Lead Technical Support Engineer',
    'Onboarding Specialist',
    'Principal Application Support Engineer',
    'Principal Customer Service Executive',
    'Principal Customer Support Executive',
    'Principal Help Desk Analyst',
    'Principal Implementation Specialist',
    'Principal Onboarding Specialist',
    'Principal Service Desk Analyst',
    'Principal Technical Support Engineer',
    'Senior Application Support Engineer',
    'Senior Customer Service Executive',
    'Senior Customer Support Executive',
    'Senior Help Desk Analyst',
    'Senior Implementation Specialist',
    'Senior Onboarding Specialist',
    'Senior Service Desk Analyst',
    'Senior Technical Support Engineer',
    'Service Desk Analyst',
    'Support Manager',
    'Technical Support Engineer'
  ],
  'Data Science & Analytics': [
    'Analytics Engineer',
    'Applied Scientist',
    'BI Analyst',
    'Business Intelligence Analyst',
    'Data Analyst',
    'Data Governance Manager',
    'Data Scientist',
    'Data Steward',
    'Data Visualization Specialist',
    'Decision Scientist',
    'Economist',
    'Junior Analytics Engineer',
    'Junior Applied Scientist',
    'Junior BI Analyst',
    'Junior Business Intelligence Analyst',
    'Junior Data Analyst',
    'Junior Data Scientist',
    'Junior Data Visualization Specialist',
    'Junior Decision Scientist',
    'Junior ML Ops Engineer',
    'Junior Quantitative Analyst',
    'Junior Research Scientist',
    'Junior Senior Data Analyst',
    'Junior Senior Data Scientist',
    'Lead Analytics Engineer',
    'Lead Applied Scientist',
    'Lead BI Analyst',
    'Lead Business Intelligence Analyst',
    'Lead Data Analyst',
    'Lead Data Scientist',
    'Lead Data Visualization Specialist',
    'Lead Decision Scientist',
    'Lead ML Ops Engineer',
    'Lead Quantitative Analyst',
    'Lead Research Scientist',
    'Lead Senior Data Analyst',
    'Lead Senior Data Scientist',
    'ML Ops Engineer',
    'Principal Analytics Engineer',
    'Principal Applied Scientist',
    'Principal BI Analyst',
    'Principal Business Intelligence Analyst',
    'Principal Data Analyst',
    'Principal Data Scientist',
    'Principal Data Visualization Specialist',
    'Principal Decision Scientist',
    'Principal ML Ops Engineer',
    'Principal Quantitative Analyst',
    'Principal Research Scientist',
    'Principal Senior Data Analyst',
    'Principal Senior Data Scientist',
    'Quantitative Analyst',
    'Research Scientist',
    'Senior Analytics Engineer',
    'Senior Applied Scientist',
    'Senior BI Analyst',
    'Senior Business Intelligence Analyst',
    'Senior Data Analyst',
    'Senior Data Scientist',
    'Senior Data Visualization Specialist',
    'Senior Decision Scientist',
    'Senior ML Ops Engineer',
    'Senior Quantitative Analyst',
    'Senior Research Scientist',
    'Senior Senior Data Analyst',
    'Senior Senior Data Scientist',
    'Statistician'
  ],
  'Design, UX & Creative': [
    'Animator',
    'Art Director',
    'Brand Designer',
    'Creative Designer',
    'Creative Director',
    'Design Researcher',
    'Graphic Designer',
    'Illustrator',
    'Interaction Designer',
    'Junior Brand Designer',
    'Junior Creative Designer',
    'Junior Graphic Designer',
    'Junior Interaction Designer',
    'Junior Motion Graphic Designer',
    'Junior UI Designer',
    'Junior UX Designer',
    'Junior Visual Designer',
    'Lead Brand Designer',
    'Lead Creative Designer',
    'Lead Graphic Designer',
    'Lead Interaction Designer',
    'Lead Motion Graphic Designer',
    'Lead UI Designer',
    'Lead UX Designer',
    'Lead Visual Designer',
    'Motion Graphic Designer',
    'Photographer',
    'Principal Brand Designer',
    'Principal Creative Designer',
    'Principal Graphic Designer',
    'Principal Interaction Designer',
    'Principal Motion Graphic Designer',
    'Principal UI Designer',
    'Principal UX Designer',
    'Principal Visual Designer',
    'Senior Brand Designer',
    'Senior Creative Designer',
    'Senior Graphic Designer',
    'Senior Interaction Designer',
    'Senior Motion Graphic Designer',
    'Senior UI Designer',
    'Senior UX Designer',
    'Senior Visual Designer',
    'UI Designer',
    'UX Designer',
    'UX Researcher',
    'Video Editor',
    'Visual Designer'
  ],
  'Drivers & Transport': [
    'Ambulance Driver',
    'Bus Driver',
    'Captain',
    'Chauffeur',
    'Co-Pilot',
    'Crane Driver',
    'Deckhand',
    'Delivery Driver',
    'Fire Truck Driver',
    'Forklift Driver',
    'Heavy Vehicle Driver',
    'Helicopter Pilot',
    'Light Vehicle Driver',
    'Pilot',
    'Seafarer',
    'Ship Engineer',
    'Taxi Driver'
  ],
  'Education & Training': [
    'Academic Coordinator',
    'Assistant Professor',
    'Corporate Trainer',
    'Curriculum Designer',
    'Instructional Designer',
    'Junior Academic Coordinator',
    'Junior Curriculum Designer',
    'Junior Instructional Designer',
    'Junior L&D Specialist',
    'Junior School Administrator',
    'Junior Training Coordinator',
    'L&D Specialist',
    'Lead Academic Coordinator',
    'Lead Curriculum Designer',
    'Lead Instructional Designer',
    'Lead L&D Specialist',
    'Lead School Administrator',
    'Lead Training Coordinator',
    'Lecturer',
    'Primary Teacher',
    'Principal Academic Coordinator',
    'Principal Curriculum Designer',
    'Principal Instructional Designer',
    'Principal L&D Specialist',
    'Principal School Administrator',
    'Principal Training Coordinator',
    'Professor',
    'School Administrator',
    'Secondary Teacher',
    'Senior Academic Coordinator',
    'Senior Curriculum Designer',
    'Senior Instructional Designer',
    'Senior L&D Specialist',
    'Senior School Administrator',
    'Senior Training Coordinator',
    'Teacher',
    'Training Coordinator'
  ],
  'Finance & Accounting': [
    'Accountant',
    'Accounts Executive',
    'Accounts Officer',
    'Accounts Payable Executive',
    'Accounts Receivable Executive',
    'Assistant Manager Finance',
    'Audit Manager',
    'Chartered Accountant',
    'Chief Financial Officer',
    'Company Secretary',
    'Cost Accountant',
    'External Auditor',
    'FP&A Manager',
    'Finance Controller',
    'Finance Manager',
    'Financial Analyst',
    'Internal Auditor',
    'Junior Accountant',
    'Junior Accounts Executive',
    'Junior Accounts Payable Executive',
    'Junior Accounts Receivable Executive',
    'Junior Chartered Accountant',
    'Junior Cost Accountant',
    'Junior Financial Analyst',
    'Junior Payroll Accountant',
    'Junior Senior Accountant',
    'Junior Senior Financial Analyst',
    'Junior Tax Analyst',
    'Junior Treasury Analyst',
    'Lead Accountant',
    'Lead Accounts Executive',
    'Lead Accounts Payable Executive',
    'Lead Accounts Receivable Executive',
    'Lead Chartered Accountant',
    'Lead Cost Accountant',
    'Lead Financial Analyst',
    'Lead Payroll Accountant',
    'Lead Senior Accountant',
    'Lead Senior Financial Analyst',
    'Lead Tax Analyst',
    'Lead Treasury Analyst',
    'Payroll Accountant',
    'Principal Accountant',
    'Principal Accounts Executive',
    'Principal Accounts Payable Executive',
    'Principal Accounts Receivable Executive',
    'Principal Chartered Accountant',
    'Principal Cost Accountant',
    'Principal Financial Analyst',
    'Principal Payroll Accountant',
    'Principal Senior Accountant',
    'Principal Senior Financial Analyst',
    'Principal Tax Analyst',
    'Principal Treasury Analyst',
    'Senior Accountant',
    'Senior Accounts Executive',
    'Senior Accounts Payable Executive',
    'Senior Accounts Receivable Executive',
    'Senior Chartered Accountant',
    'Senior Cost Accountant',
    'Senior Finance Manager',
    'Senior Financial Analyst',
    'Senior Payroll Accountant',
    'Senior Senior Accountant',
    'Senior Senior Financial Analyst',
    'Senior Tax Analyst',
    'Senior Treasury Analyst',
    'Tax Analyst',
    'Tax Associate',
    'Tax Manager',
    'Treasury Analyst',
    'Treasury Manager'
  ],
  'Healthcare & Life Sciences': [
    'Clinical Data Manager',
    'Clinical Research Associate',
    'Dentist',
    'General Physician',
    'Junior Lab Technician',
    'Junior Radiology Technician',
    'Lab Technician',
    'Lead Lab Technician',
    'Lead Radiology Technician',
    'Medical Coder',
    'Medical Officer',
    'Nutritionist',
    'Pharmacist',
    'Physiotherapist',
    'Principal Lab Technician',
    'Principal Radiology Technician',
    'Radiology Technician',
    'Registered Nurse',
    'Senior Lab Technician',
    'Senior Radiology Technician',
    'Staff Nurse',
    'Surgeon'
  ],
  'Hospitality & Domestic': [
    'Bouncer',
    'Caretaker',
    'Cook',
    'Domestic Worker',
    'Housekeeper',
    'Janitor',
    'Kitchen Helper',
    'Laundry Attendant',
    'Nanny',
    'Room Attendant',
    'Security Guard',
    'Steward',
    'Watchman'
  ],
  'Hospitality, Travel & Retail': [
    'Baker',
    'Barista',
    'Bartender',
    'Cashier',
    'Chef',
    'Commis Chef',
    'F&B Manager',
    'Front Office Manager',
    'Guest Relations Executive',
    'Housekeeping Supervisor',
    'Junior Guest Relations Executive',
    'Junior Travel Consultant',
    'Lead Guest Relations Executive',
    'Lead Travel Consultant',
    'Pastry Chef',
    'Principal Guest Relations Executive',
    'Principal Travel Consultant',
    'Restaurant Manager',
    'Retail Sales Associate',
    'Senior Guest Relations Executive',
    'Senior Travel Consultant',
    'Sous Chef',
    'Store Manager',
    'Ticketing Agent',
    'Travel Consultant',
    'Visual Merchandiser',
    'Waiter'
  ],
  'Human Resources & Talent': [
    'Campus Recruiter',
    'Chief Human Resources Officer',
    'Compensation and Benefits Analyst',
    'Compensation and Benefits Manager',
    'Employee Relations Specialist',
    'HR Business Partner',
    'HR Coordinator',
    'HR Director',
    'HR Executive',
    'HR Generalist',
    'HR Intern',
    'HR Manager',
    'HRIS Analyst',
    'Head of HR',
    'Junior Compensation and Benefits Analyst',
    'Junior Employee Relations Specialist',
    'Junior HR Coordinator',
    'Junior HR Executive',
    'Junior HRIS Analyst',
    'Junior Learning and Development Specialist',
    'Junior Payroll Executive',
    'Junior Payroll Specialist',
    'Junior Recruitment Consultant',
    'Junior Senior Talent Acquisition Specialist',
    'Junior Talent Acquisition Executive',
    'Junior Talent Acquisition Specialist',
    'Lead Compensation and Benefits Analyst',
    'Lead Employee Relations Specialist',
    'Lead HR Coordinator',
    'Lead HR Executive',
    'Lead HRIS Analyst',
    'Lead Learning and Development Specialist',
    'Lead Payroll Executive',
    'Lead Payroll Specialist',
    'Lead Recruitment Consultant',
    'Lead Senior Talent Acquisition Specialist',
    'Lead Talent Acquisition Executive',
    'Lead Talent Acquisition Specialist',
    'Learning and Development Specialist',
    'Organizational Development Manager',
    'Payroll Executive',
    'Payroll Specialist',
    'Principal Compensation and Benefits Analyst',
    'Principal Employee Relations Specialist',
    'Principal HR Coordinator',
    'Principal HR Executive',
    'Principal HRIS Analyst',
    'Principal Learning and Development Specialist',
    'Principal Payroll Executive',
    'Principal Payroll Specialist',
    'Principal Recruitment Consultant',
    'Principal Senior Talent Acquisition Specialist',
    'Principal Talent Acquisition Executive',
    'Principal Talent Acquisition Specialist',
    'Recruitment Consultant',
    'Recruitment Manager',
    'Senior Compensation and Benefits Analyst',
    'Senior Employee Relations Specialist',
    'Senior HR Business Partner',
    'Senior HR Coordinator',
    'Senior HR Executive',
    'Senior HR Generalist',
    'Senior HR Manager',
    'Senior HRIS Analyst',
    'Senior Learning and Development Specialist',
    'Senior Payroll Executive',
    'Senior Payroll Specialist',
    'Senior Recruitment Consultant',
    'Senior Senior Talent Acquisition Specialist',
    'Senior Talent Acquisition Executive',
    'Senior Talent Acquisition Specialist',
    'Talent Acquisition Executive',
    'Talent Acquisition Intern',
    'Talent Acquisition Manager',
    'Talent Acquisition Specialist',
    'Talent Sourcer',
    'Technical Recruiter',
    'Training Manager'
  ],
  'Legal, Risk & Compliance': [
    'Associate Lawyer',
    'Compliance Analyst',
    'Compliance Manager',
    'Corporate Lawyer',
    'Data Protection Officer',
    'Head of Legal',
    'Junior Compliance Analyst',
    'Junior Risk Analyst',
    'Lead Compliance Analyst',
    'Lead Risk Analyst',
    'Legal Assistant',
    'Legal Counsel',
    'Paralegal',
    'Principal Compliance Analyst',
    'Principal Risk Analyst',
    'Risk Analyst',
    'Risk Manager',
    'Senior Compliance Analyst',
    'Senior Legal Counsel',
    'Senior Risk Analyst'
  ],
  'Logistics & Transportation': [
    'Air Freight Executive',
    'Courier',
    'Customs Broker',
    'Dispatcher',
    'Driver',
    'Fleet Coordinator',
    'Fleet Manager',
    'Junior Air Freight Executive',
    'Junior Fleet Coordinator',
    'Junior Ocean Freight Executive',
    'Junior Shipping Coordinator',
    'Lead Air Freight Executive',
    'Lead Fleet Coordinator',
    'Lead Ocean Freight Executive',
    'Lead Shipping Coordinator',
    'Ocean Freight Executive',
    'Principal Air Freight Executive',
    'Principal Fleet Coordinator',
    'Principal Ocean Freight Executive',
    'Principal Shipping Coordinator',
    'Route Planner',
    'Senior Air Freight Executive',
    'Senior Fleet Coordinator',
    'Senior Ocean Freight Executive',
    'Senior Shipping Coordinator',
    'Shipping Coordinator',
    'Truck Driver'
  ],
  'Manufacturing & Production Workers': [
    'Assembly Line Worker',
    'Cleaner',
    'Helper',
    'Housekeeping Staff',
    'Loader',
    'Machine Operator',
    'Material Handler',
    'Packaging Worker',
    'Packer',
    'Packing Operator',
    'Picker',
    'Production Worker',
    'Unloader',
    'Warehouse Worker'
  ],
  'Manufacturing, Quality & EHS': [
    'Continuous Improvement Engineer',
    'EHS Engineer',
    'EHS Manager',
    'EHS Officer',
    'Industrial Engineer',
    'Junior Continuous Improvement Engineer',
    'Junior EHS Engineer',
    'Junior Industrial Engineer',
    'Junior Lean Manufacturing Engineer',
    'Junior Maintenance Engineer',
    'Junior Maintenance Technician',
    'Junior Manufacturing Engineer',
    'Junior Process Engineer',
    'Junior Production Engineer',
    'Junior Production Operator',
    'Junior QA/QC Engineer',
    'Junior Quality Analyst',
    'Junior Quality Engineer',
    'Lead Continuous Improvement Engineer',
    'Lead EHS Engineer',
    'Lead Industrial Engineer',
    'Lead Lean Manufacturing Engineer',
    'Lead Maintenance Engineer',
    'Lead Maintenance Technician',
    'Lead Manufacturing Engineer',
    'Lead Process Engineer',
    'Lead Production Engineer',
    'Lead Production Operator',
    'Lead QA/QC Engineer',
    'Lead Quality Analyst',
    'Lead Quality Engineer',
    'Lean Manufacturing Engineer',
    'Maintenance Engineer',
    'Maintenance Technician',
    'Manufacturing Engineer',
    'Plant Manager',
    'Principal Continuous Improvement Engineer',
    'Principal EHS Engineer',
    'Principal Industrial Engineer',
    'Principal Lean Manufacturing Engineer',
    'Principal Maintenance Engineer',
    'Principal Maintenance Technician',
    'Principal Manufacturing Engineer',
    'Principal Process Engineer',
    'Principal Production Engineer',
    'Principal Production Operator',
    'Principal QA/QC Engineer',
    'Principal Quality Analyst',
    'Principal Quality Engineer',
    'Process Engineer',
    'Production Engineer',
    'Production Operator',
    'Production Supervisor',
    'QA/QC Engineer',
    'Quality Analyst',
    'Quality Engineer',
    'Quality Inspector',
    'Quality Manager',
    'Senior Continuous Improvement Engineer',
    'Senior EHS Engineer',
    'Senior Industrial Engineer',
    'Senior Lean Manufacturing Engineer',
    'Senior Maintenance Engineer',
    'Senior Maintenance Technician',
    'Senior Manufacturing Engineer',
    'Senior Process Engineer',
    'Senior Production Engineer',
    'Senior Production Operator',
    'Senior QA/QC Engineer',
    'Senior Quality Analyst',
    'Senior Quality Engineer'
  ],
  'Marketing & Communications': [
    'Brand Manager',
    'Chief Marketing Officer',
    'Communications Manager',
    'Community Manager',
    'Content Strategist',
    'Content Writer',
    'Copywriter',
    'Digital Marketing Executive',
    'Digital Marketing Manager',
    'Director of Marketing',
    'Events Manager',
    'Growth Marketing Manager',
    'Head of Marketing',
    'Junior Digital Marketing Executive',
    'Junior Marketing Executive',
    'Junior PPC Specialist',
    'Junior PR Executive',
    'Junior SEM Specialist',
    'Junior SEO Specialist',
    'Junior Social Media Executive',
    'Lead Digital Marketing Executive',
    'Lead Marketing Executive',
    'Lead PPC Specialist',
    'Lead PR Executive',
    'Lead SEM Specialist',
    'Lead SEO Specialist',
    'Lead Social Media Executive',
    'Marketing Associate',
    'Marketing Executive',
    'Marketing Manager',
    'PPC Specialist',
    'PR Executive',
    'PR Manager',
    'Performance Marketing Manager',
    'Principal Digital Marketing Executive',
    'Principal Marketing Executive',
    'Principal PPC Specialist',
    'Principal PR Executive',
    'Principal SEM Specialist',
    'Principal SEO Specialist',
    'Principal Social Media Executive',
    'Product Marketing Manager',
    'SEM Specialist',
    'SEO Specialist',
    'Senior Digital Marketing Executive',
    'Senior Marketing Executive',
    'Senior Marketing Manager',
    'Senior PPC Specialist',
    'Senior PR Executive',
    'Senior SEM Specialist',
    'Senior SEO Specialist',
    'Senior Social Media Executive',
    'Social Media Executive',
    'Social Media Manager',
    'VP of Marketing'
  ],
  'Media, Content & Design': [
    'Content Editor',
    'Content Manager',
    'Digital Content Specialist',
    'Junior Digital Content Specialist',
    'Junior PR Specialist',
    'Junior Social Media Coordinator',
    'Lead Digital Content Specialist',
    'Lead PR Specialist',
    'Lead Social Media Coordinator',
    'PR Specialist',
    'Podcast Producer',
    'Principal Digital Content Specialist',
    'Principal PR Specialist',
    'Principal Social Media Coordinator',
    'SEO Content Writer',
    'Senior Content Writer',
    'Senior Digital Content Specialist',
    'Senior PR Specialist',
    'Senior Social Media Coordinator',
    'Social Media Coordinator',
    'Video Producer'
  ],
  'Operations, Administration & Procurement': [
    'Admin Executive',
    'Back Office Executive',
    'Business Operations Manager',
    'COO',
    'Category Manager',
    'Demand Planner',
    'Executive Assistant',
    'Facilities Executive',
    'Facilities Manager',
    'Front Office Executive',
    'Head of Operations',
    'Import Export Executive',
    'Inventory Controller',
    'Junior Admin Executive',
    'Junior Back Office Executive',
    'Junior Executive Assistant',
    'Junior Facilities Executive',
    'Junior Front Office Executive',
    'Junior Import Export Executive',
    'Junior Logistics Coordinator',
    'Junior Office Administrator',
    'Junior Operations Analyst',
    'Junior Operations Executive',
    'Junior Procurement Executive',
    'Junior Sourcing Specialist',
    'Junior Supply Chain Analyst',
    'Junior Travel Coordinator',
    'Lead Admin Executive',
    'Lead Back Office Executive',
    'Lead Executive Assistant',
    'Lead Facilities Executive',
    'Lead Front Office Executive',
    'Lead Import Export Executive',
    'Lead Logistics Coordinator',
    'Lead Office Administrator',
    'Lead Operations Analyst',
    'Lead Operations Executive',
    'Lead Procurement Executive',
    'Lead Sourcing Specialist',
    'Lead Supply Chain Analyst',
    'Lead Travel Coordinator',
    'Logistics Coordinator',
    'Logistics Manager',
    'Office Administrator',
    'Office Manager',
    'Operations Analyst',
    'Operations Executive',
    'Operations Manager',
    'Personal Assistant',
    'Principal Admin Executive',
    'Principal Back Office Executive',
    'Principal Executive Assistant',
    'Principal Facilities Executive',
    'Principal Front Office Executive',
    'Principal Import Export Executive',
    'Principal Logistics Coordinator',
    'Principal Office Administrator',
    'Principal Operations Analyst',
    'Principal Operations Executive',
    'Principal Procurement Executive',
    'Principal Sourcing Specialist',
    'Principal Supply Chain Analyst',
    'Principal Travel Coordinator',
    'Procurement Executive',
    'Procurement Manager',
    'Production Planner',
    'Receptionist',
    'Senior Admin Executive',
    'Senior Back Office Executive',
    'Senior Executive Assistant',
    'Senior Facilities Executive',
    'Senior Front Office Executive',
    'Senior Import Export Executive',
    'Senior Logistics Coordinator',
    'Senior Office Administrator',
    'Senior Operations Analyst',
    'Senior Operations Executive',
    'Senior Operations Manager',
    'Senior Procurement Executive',
    'Senior Sourcing Specialist',
    'Senior Supply Chain Analyst',
    'Senior Travel Coordinator',
    'Sourcing Specialist',
    'Store Keeper',
    'Strategy & Operations Manager',
    'Supply Chain Analyst',
    'Supply Chain Manager',
    'Transport Manager',
    'Travel Coordinator',
    'Vendor Manager',
    'Warehouse Manager',
    'Warehouse Supervisor'
  ],
  'Product Management & Analysis': [
    'Associate Product Manager',
    'Business Analyst',
    'Chief Product Officer',
    'Director of Product',
    'Group Product Manager',
    'Head of Product',
    'Junior Business Analyst',
    'Junior Product Analyst',
    'Junior Product Designer',
    'Junior Systems Analyst',
    'Junior Technical Business Analyst',
    'Lead Business Analyst',
    'Lead Product Analyst',
    'Lead Product Designer',
    'Lead Systems Analyst',
    'Lead Technical Business Analyst',
    'Principal Business Analyst',
    'Principal Product Analyst',
    'Principal Product Designer',
    'Principal Product Manager',
    'Principal Systems Analyst',
    'Principal Technical Business Analyst',
    'Product Analyst',
    'Product Designer',
    'Product Manager',
    'Product Operations Manager',
    'Product Owner',
    'Senior Business Analyst',
    'Senior Product Analyst',
    'Senior Product Designer',
    'Senior Product Manager',
    'Senior Systems Analyst',
    'Senior Technical Business Analyst',
    'Systems Analyst',
    'Technical Business Analyst',
    'VP of Product'
  ],
  'Project, Program & PMO': [
    'Agile Coach',
    'Delivery Manager',
    'Engagement Manager',
    'Junior PMO Analyst',
    'Junior Program Coordinator',
    'Junior Project Coordinator',
    'Lead PMO Analyst',
    'Lead Program Coordinator',
    'Lead Project Coordinator',
    'PMO Analyst',
    'PMO Manager',
    'Portfolio Manager',
    'Principal PMO Analyst',
    'Principal Program Coordinator',
    'Principal Project Coordinator',
    'Program Coordinator',
    'Program Manager',
    'Project Coordinator',
    'Project Manager',
    'Scrum Master',
    'Senior PMO Analyst',
    'Senior Program Coordinator',
    'Senior Project Coordinator',
    'Senior Project Manager'
  ],
  'Sales (Inside, Field, Key Accounts)': [
    'Alliance Manager',
    'Area Sales Manager',
    'Business Development Associate',
    'Business Development Executive',
    'Business Development Manager',
    'Channel Sales Manager',
    'Customer Success Manager',
    'Enterprise Account Executive',
    'Field Sales Executive',
    'Inside Sales Executive',
    'Inside Sales Representative',
    'Junior Business Development Executive',
    'Junior Enterprise Account Executive',
    'Junior Field Sales Executive',
    'Junior Inside Sales Executive',
    'Junior Key Account Executive',
    'Junior Pre-Sales Engineer',
    'Junior Sales Engineer',
    'Junior Sales Executive',
    'Junior Solutions Consultant',
    'Junior Telesales Executive',
    'Key Account Executive',
    'Key Account Manager',
    'Lead Business Development Executive',
    'Lead Enterprise Account Executive',
    'Lead Field Sales Executive',
    'Lead Inside Sales Executive',
    'Lead Key Account Executive',
    'Lead Pre-Sales Engineer',
    'Lead Sales Engineer',
    'Lead Sales Executive',
    'Lead Solutions Consultant',
    'Lead Telesales Executive',
    'National Sales Manager',
    'Partnerships Manager',
    'Pre-Sales Engineer',
    'Principal Business Development Executive',
    'Principal Enterprise Account Executive',
    'Principal Field Sales Executive',
    'Principal Inside Sales Executive',
    'Principal Key Account Executive',
    'Principal Pre-Sales Engineer',
    'Principal Sales Engineer',
    'Principal Sales Executive',
    'Principal Solutions Consultant',
    'Principal Telesales Executive',
    'Regional Sales Manager',
    'Relationship Manager',
    'Renewals Manager',
    'Sales Engineer',
    'Sales Executive',
    'Sales Manager',
    'Sales Representative',
    'Senior Business Development Executive',
    'Senior Business Development Manager',
    'Senior Enterprise Account Executive',
    'Senior Field Sales Executive',
    'Senior Inside Sales Executive',
    'Senior Key Account Executive',
    'Senior Pre-Sales Engineer',
    'Senior Sales Engineer',
    'Senior Sales Executive',
    'Senior Solutions Consultant',
    'Senior Telesales Executive',
    'Solutions Consultant',
    'Telecaller',
    'Telesales Executive',
    'Territory Sales Manager',
    'Zonal Sales Manager'
  ],
  'Skilled Trades & Technicians': [
    'AC Mechanic',
    'Automobile Mechanic',
    'Aviation Technician',
    'Backhoe Operator',
    'Blacksmith',
    'Blaster',
    'Boilermaker',
    'Bulldozer Operator',
    'CNC Operator',
    'CNC Programmer',
    'Carpenter',
    'Casting Operator',
    'Crane Operator',
    'Diesel Mechanic',
    'Driller',
    'Electrical Technician',
    'Electrician',
    'Elevator Technician',
    'Excavator Operator',
    'Fabricator',
    'Fitter',
    'Forging Operator',
    'Forklift Operator',
    'Foundry Worker',
    'Four-Wheeler Mechanic',
    'Furnace Technician',
    'Generator Technician',
    'Glass Technician',
    'Grinder',
    'HVAC Technician',
    'Heat Treatment Operator',
    'Heavy Equipment Operator',
    'Lathe Operator',
    'Machinist',
    'Marine Mechanic',
    'Mason',
    'Mechanical Technician',
    'Miller',
    'Mining Technician',
    'Offshore Technician',
    'Oil Rig Worker',
    'Painter',
    'Pipe Fitter',
    'Plasterer',
    'Plumber',
    'Polisher',
    'Pump Technician',
    'Quarry Worker',
    'Refrigeration Technician',
    'Rig Supervisor',
    'Rigger',
    'Scaffolder',
    'Sheet Metal Worker',
    'Tile Setter',
    'Tool and Die Maker',
    'Truck Mechanic',
    'Turner',
    'Two-Wheeler Mechanic',
    'Welder'
  ],
  'Software Engineering & IT': [
    'AI Engineer',
    'AR/VR Developer',
    'Android Developer',
    'Application Developer',
    'Automation Engineer',
    'BI Developer',
    'Backend Engineer',
    'Big Data Engineer',
    'CIO',
    'Cloud Engineer',
    'Cybersecurity Engineer',
    'Data Engineer',
    'Data Platform Engineer',
    'Data Warehouse Developer',
    'Database Administrator',
    'DevOps Engineer',
    'Dynamics 365 Consultant',
    'ERP Consultant',
    'ETL Developer',
    'ETL Tester',
    'Embedded Engineer',
    'Enterprise Architect',
    'Firmware Engineer',
    'Frontend Engineer',
    'Full Stack Engineer',
    'GRC Analyst',
    'Game Developer',
    'IT Administrator',
    'IT Coordinator',
    'IT Director',
    'IT Helpdesk Technician',
    'IT Manager',
    'IT Operations Engineer',
    'IT Service Desk Analyst',
    'IT Support Engineer',
    'IT Support Specialist',
    'Information Security Analyst',
    'Integration Engineer',
    'Junior AI Engineer',
    'Junior AR/VR Developer',
    'Junior Android Developer',
    'Junior Application Developer',
    'Junior Automation Engineer',
    'Junior BI Developer',
    'Junior Backend Engineer',
    'Junior Big Data Engineer',
    'Junior Cloud Engineer',
    'Junior Cybersecurity Engineer',
    'Junior Data Engineer',
    'Junior Data Platform Engineer',
    'Junior Data Warehouse Developer',
    'Junior Database Administrator',
    'Junior DevOps Engineer',
    'Junior Dynamics 365 Consultant',
    'Junior ERP Consultant',
    'Junior ETL Developer',
    'Junior Embedded Engineer',
    'Junior Firmware Engineer',
    'Junior Frontend Engineer',
    'Junior Full Stack Engineer',
    'Junior GRC Analyst',
    'Junior Game Developer',
    'Junior IT Administrator',
    'Junior IT Coordinator',
    'Junior IT Helpdesk Technician',
    'Junior IT Operations Engineer',
    'Junior IT Service Desk Analyst',
    'Junior IT Support Engineer',
    'Junior IT Support Specialist',
    'Junior Information Security Analyst',
    'Junior Integration Engineer',
    'Junior Machine Learning Engineer',
    'Junior Mobile Developer',
    'Junior Network Administrator',
    'Junior Network Engineer',
    'Junior Observability Engineer',
    'Junior Oracle EBS Consultant',
    'Junior Platform Engineer',
    'Junior QA Engineer',
    'Junior SAP ABAP Developer',
    'Junior SAP Consultant',
    'Junior SAP FICO Consultant',
    'Junior SAP MM Consultant',
    'Junior SAP SD Consultant',
    'Junior SOC Analyst',
    'Junior SQL Developer',
    'Junior Security Analyst',
    'Junior Security Engineer',
    'Junior Site Reliability Engineer',
    'Junior Software Engineer',
    'Junior System Administrator',
    'Junior Systems Engineer',
    'Junior Vulnerability Analyst',
    'Junior Web Developer',
    'Junior iOS Developer',
    'Lead AI Engineer',
    'Lead AR/VR Developer',
    'Lead Android Developer',
    'Lead Application Developer',
    'Lead Automation Engineer',
    'Lead BI Developer',
    'Lead Backend Engineer',
    'Lead Big Data Engineer',
    'Lead Cloud Engineer',
    'Lead Cybersecurity Engineer',
    'Lead Data Engineer',
    'Lead Data Platform Engineer',
    'Lead Data Warehouse Developer',
    'Lead Database Administrator',
    'Lead DevOps Engineer',
    'Lead Dynamics 365 Consultant',
    'Lead ERP Consultant',
    'Lead ETL Developer',
    'Lead Embedded Engineer',
    'Lead Firmware Engineer',
    'Lead Frontend Engineer',
    'Lead Full Stack Engineer',
    'Lead GRC Analyst',
    'Lead Game Developer',
    'Lead IT Administrator',
    'Lead IT Coordinator',
    'Lead IT Helpdesk Technician',
    'Lead IT Operations Engineer',
    'Lead IT Service Desk Analyst',
    'Lead IT Support Engineer',
    'Lead IT Support Specialist',
    'Lead Information Security Analyst',
    'Lead Integration Engineer',
    'Lead Machine Learning Engineer',
    'Lead Mobile Developer',
    'Lead Network Administrator',
    'Lead Network Engineer',
    'Lead Observability Engineer',
    'Lead Oracle EBS Consultant',
    'Lead Platform Engineer',
    'Lead QA Engineer',
    'Lead SAP ABAP Developer',
    'Lead SAP Consultant',
    'Lead SAP FICO Consultant',
    'Lead SAP MM Consultant',
    'Lead SAP SD Consultant',
    'Lead SOC Analyst',
    'Lead SQL Developer',
    'Lead Security Analyst',
    'Lead Security Engineer',
    'Lead Site Reliability Engineer',
    'Lead Software Engineer',
    'Lead System Administrator',
    'Lead Systems Engineer',
    'Lead Vulnerability Analyst',
    'Lead Web Developer',
    'Lead iOS Developer',
    'Machine Learning Engineer',
    'Mobile Developer',
    'Network Administrator',
    'Network Engineer',
    'Observability Engineer',
    'Oracle DBA',
    'Oracle EBS Consultant',
    'Penetration Tester',
    'Platform Engineer',
    'Principal AI Engineer',
    'Principal AR/VR Developer',
    'Principal Android Developer',
    'Principal Application Developer',
    'Principal Automation Engineer',
    'Principal BI Developer',
    'Principal Backend Engineer',
    'Principal Big Data Engineer',
    'Principal Cloud Engineer',
    'Principal Cybersecurity Engineer',
    'Principal Data Engineer',
    'Principal Data Platform Engineer',
    'Principal Data Warehouse Developer',
    'Principal Database Administrator',
    'Principal DevOps Engineer',
    'Principal Dynamics 365 Consultant',
    'Principal ERP Consultant',
    'Principal ETL Developer',
    'Principal Embedded Engineer',
    'Principal Firmware Engineer',
    'Principal Frontend Engineer',
    'Principal Full Stack Engineer',
    'Principal GRC Analyst',
    'Principal Game Developer',
    'Principal IT Administrator',
    'Principal IT Coordinator',
    'Principal IT Helpdesk Technician',
    'Principal IT Operations Engineer',
    'Principal IT Service Desk Analyst',
    'Principal IT Support Engineer',
    'Principal IT Support Specialist',
    'Principal Information Security Analyst',
    'Principal Integration Engineer',
    'Principal Machine Learning Engineer',
    'Principal Mobile Developer',
    'Principal Network Administrator',
    'Principal Network Engineer',
    'Principal Observability Engineer',
    'Principal Oracle EBS Consultant',
    'Principal Platform Engineer',
    'Principal QA Engineer',
    'Principal SAP ABAP Developer',
    'Principal SAP Consultant',
    'Principal SAP FICO Consultant',
    'Principal SAP MM Consultant',
    'Principal SAP SD Consultant',
    'Principal SOC Analyst',
    'Principal SQL Developer',
    'Principal Security Analyst',
    'Principal Security Engineer',
    'Principal Site Reliability Engineer',
    'Principal Software Engineer',
    'Principal System Administrator',
    'Principal Systems Engineer',
    'Principal Vulnerability Analyst',
    'Principal Web Developer',
    'Principal iOS Developer',
    'QA Engineer',
    'SAP ABAP Developer',
    'SAP Consultant',
    'SAP FICO Consultant',
    'SAP MM Consultant',
    'SAP SD Consultant',
    'SDET',
    'SOC Analyst',
    'SQL Developer',
    'Security Analyst',
    'Security Engineer',
    'Senior AI Engineer',
    'Senior AR/VR Developer',
    'Senior Android Developer',
    'Senior Application Developer',
    'Senior Automation Engineer',
    'Senior BI Developer',
    'Senior Backend Engineer',
    'Senior Big Data Engineer',
    'Senior Cloud Engineer',
    'Senior Cybersecurity Engineer',
    'Senior Data Engineer',
    'Senior Data Platform Engineer',
    'Senior Data Warehouse Developer',
    'Senior Database Administrator',
    'Senior DevOps Engineer',
    'Senior Dynamics 365 Consultant',
    'Senior ERP Consultant',
    'Senior ETL Developer',
    'Senior Embedded Engineer',
    'Senior Firmware Engineer',
    'Senior Frontend Engineer',
    'Senior Full Stack Engineer',
    'Senior GRC Analyst',
    'Senior Game Developer',
    'Senior IT Administrator',
    'Senior IT Coordinator',
    'Senior IT Helpdesk Technician',
    'Senior IT Operations Engineer',
    'Senior IT Service Desk Analyst',
    'Senior IT Support Engineer',
    'Senior IT Support Specialist',
    'Senior Information Security Analyst',
    'Senior Integration Engineer',
    'Senior Machine Learning Engineer',
    'Senior Mobile Developer',
    'Senior Network Administrator',
    'Senior Network Engineer',
    'Senior Observability Engineer',
    'Senior Oracle EBS Consultant',
    'Senior Platform Engineer',
    'Senior QA Engineer',
    'Senior SAP ABAP Developer',
    'Senior SAP Consultant',
    'Senior SAP FICO Consultant',
    'Senior SAP MM Consultant',
    'Senior SAP SD Consultant',
    'Senior SOC Analyst',
    'Senior SQL Developer',
    'Senior Security Analyst',
    'Senior Security Engineer',
    'Senior Site Reliability Engineer',
    'Senior Software Engineer',
    'Senior System Administrator',
    'Senior Systems Engineer',
    'Senior Vulnerability Analyst',
    'Senior Web Developer',
    'Senior iOS Developer',
    'Site Reliability Engineer',
    'Software Engineer',
    'Solution Architect',
    'System Administrator',
    'Systems Engineer',
    'Vulnerability Analyst',
    'Web Developer',
    'iOS Developer'
  ],
  'Other': [
    'Other'
  ]
};

// Nationalities list
export const nationalities = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Antiguans',
  'Argentinean',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Barbudans',
  'Batswana',
  'Belarusian',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinabe',
  'Burmese',
  'Burundian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comoran',
  'Congolese',
  'Costa Rican',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djibouti',
  'Dominican',
  'Dutch',
  'East Timorese',
  'Ecuadorean',
  'Egyptian',
  'Emirian',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinea-Bissauan',
  'Guinean',
  'Guyanese',
  'Haitian',
  'Herzegovinian',
  'Honduran',
  'Hungarian',
  'I-Kiribati',
  'Icelander',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kenyan',
  'Kittian and Nevisian',
  'Kuwaiti',
  'Kyrgyz',
  'Laotian',
  'Latvian',
  'Lebanese',
  'Liberian',
  'Libyan',
  'Liechtensteiner',
  'Lithuanian',
  'Luxembourger',
  'Macedonian',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivan',
  'Malian',
  'Maltese',
  'Marshallese',
  'Mauritanian',
  'Mauritian',
  'Mexican',
  'Micronesian',
  'Moldovan',
  'Monacan',
  'Mongolian',
  'Moroccan',
  'Mosotho',
  'Motswana',
  'Mozambican',
  'Namibian',
  'Nauruan',
  'Nepalese',
  'New Zealander',
  'Ni-Vanuatu',
  'Nicaraguan',
  'Nigerian',
  'Nigerien',
  'North Korean',
  'Northern Irish',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Palauan',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Saint Lucian',
  'Salvadoran',
  'Samoan',
  'San Marinese',
  'Sao Tomean',
  'Saudi',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sierra Leonean',
  'Singaporean',
  'Slovakian',
  'Slovenian',
  'Solomon Islander',
  'Somali',
  'South African',
  'South Korean',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamer',
  'Swazi',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Tongan',
  'Trinidadian or Tobagonian',
  'Tunisian',
  'Turkish',
  'Tuvaluan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbekistani',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'Yemenite',
  'Zambian',
  'Zimbabwean'
];

// Helper functions
export const getJobCategories = () => {
  return Object.keys(jobTitles);
};

export const getJobTitlesByCategory = (category: string) => {
  return jobTitles[category as keyof typeof jobTitles] || [];
};

export const getAllJobTitles = () => {
  const allTitles: string[] = [];
  Object.values(jobTitles).forEach(titles => {
    allTitles.push(...titles);
  });
  return allTitles.sort();
};

export const searchJobTitles = (query: string) => {
  const lowerQuery = query.toLowerCase();
  const allTitles = getAllJobTitles();
  return allTitles
    .filter(title => title.toLowerCase().includes(lowerQuery))
    .slice(0, 20); // Limit results
};

export const searchNationalities = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return nationalities
    .filter(nationality => nationality.toLowerCase().includes(lowerQuery))
    .slice(0, 20); // Limit results
};
